Repository mozilla/fxa, pull requests merged in 2019-10, with the labels that each got.

#2843 chore(npm): changed 'npm start' to run 'pm2 start mysql_servers.json'
  mysql_servers.json
  package.json
Labels: QA-

#2866 fix(css): Fix authorize sign-in screen size on mobile
  packages/fxa-content-server/app/styles/_layout.scss
Labels: [QA]:Minor issue

#3032 feat(email-first): Use email-first for CAD by default.
  packages/fxa-content-server/app/scripts/views/connect_another_device.js
  packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
  packages/fxa-content-server/tests/functional/connect_another_device.js
  packages/fxa-content-server/tests/functional/lib/helpers.js
Labels: [QA]:Enhancement

#3035 feat(email-first): Add the sync-suggestion UI to email-first flow
  packages/fxa-content-server/app/scripts/templates/index.mustache
  packages/fxa-content-server/app/scripts/views/index.js
  packages/fxa-content-server/app/scripts/views/mixins/sync-suggestion-mixin.js
  packages/fxa-content-server/app/scripts/views/sign_up.js
  packages/fxa-content-server/app/tests/spec/views/mixins/sync-suggestion-mixin.js
  packages/fxa-content-server/tests/functional/sign_up.js
Labels: [QA]:Enhancement

#2845 refactor(code): Rename token code input to otp code input and cleanup logic
  packages/fxa-content-server/app/scripts/lib/auth-errors.js
  packages/fxa-content-server/app/scripts/templates/confirm_signup_code.mustache
  packages/fxa-content-server/app/scripts/templates/sign_in_recovery_code.mustache
  packages/fxa-content-server/app/scripts/templates/sign_in_token_code.mustache
  packages/fxa-content-server/app/scripts/templates/sign_in_totp_code.mustache
  packages/fxa-content-server/app/scripts/views/confirm_signup_code.js
  packages/fxa-content-server/app/scripts/views/elements/jquery-plugin.js
  packages/fxa-content-server/app/scripts/views/elements/otp-code-input.js
  packages/fxa-content-server/app/scripts/views/sign_in_token_code.js
  packages/fxa-content-server/app/tests/spec/views/confirm_signup_code.js
  packages/fxa-content-server/app/tests/spec/views/elements/otp-code-input.js
  packages/fxa-content-server/app/tests/spec/views/sign_in_token_code.js
  packages/fxa-content-server/app/tests/test_start.js
  packages/fxa-content-server/tests/functional/lib/selectors.js
Labels: [QA]:Minor issue
