Repository mozilla/fxa, pull requests merged in 2019-04, with the labels that each got.

#361 feat(labels): Add q2 2019 labels, ditch old ones
  scripts/repos.txt
  scripts/sync_labels.js
Labels: waffle:active

#699 updated circleci deploy script for new env vars
  .circleci/deploy.sh
Labels: waffle:active

#679 chore(deps): Update deps to get rid of security warnings.
  packages/123done/package-lock.json
  packages/123done/package.json
  packages/123done/retarget.js
  packages/123done/server.js
  packages/123done/static/about.html
  packages/123done/static/index.html
Labels: waffle:review

#727 fix(teamcity): content: fix teamcity directory location
  packages/fxa-content-server/tests/teamcity/run-server.sh
  packages/fxa-content-server/tests/teamcity/run.sh
Labels: waffle:active

#728 Rerun failed functional tests on CircleCI
  .circleci/config.yml
  .circleci/test-content-server.sh
  packages/fxa-content-server/tests/intern.js
Labels: waffle:active

#680 feat(scripts): add monorepo-friendly release script
  packages/fxa-email-event-proxy/package-lock.json
  packages/fxa-email-event-proxy/package.json
  release.sh
Labels: train-135, waffle:review

#696 Removed period
  packages/fxa-content-server/app/scripts/templates/choose_what_to_sync.mustache
Labels: waffle:active

#736 fix(npm): add package-lock for geodb
  packages/fxa-geodb/package-lock.json
Labels: waffle:active

#749 fix(teamcity): actually fix teamcity directory location for real this time
  packages/fxa-content-server/tests/teamcity/run-server.sh
  packages/fxa-content-server/tests/teamcity/run.sh
Labels: waffle:active

#690 fix(scripts): ignore bouncing accounts in verification reminders
  packages/fxa-auth-server/scripts/verification-reminders.js
Labels: P2

#761 Merge train-134 into master
  .circleci/config.yml
  packages/fxa-auth-db-mysql/CHANGELOG.md
  packages/fxa-auth-db-mysql/npm-shrinkwrap.json
  packages/fxa-auth-db-mysql/package.json
  packages/fxa-auth-server/CHANGELOG.md
  packages/fxa-auth-server/npm-shrinkwrap.json
  packages/fxa-auth-server/package.json
  packages/fxa-content-server/CHANGELOG.md
  packages/fxa-content-server/package.json
  packages/fxa-customs-server/CHANGELOG.md
  packages/fxa-customs-server/npm-shrinkwrap.json
  packages/fxa-customs-server/package.json
  packages/fxa-email-event-proxy/package-lock.json
  packages/fxa-email-event-proxy/package.json
  packages/fxa-email-service/CHANGELOG.md
  packages/fxa-email-service/Cargo.lock
  packages/fxa-email-service/Cargo.toml
  packages/fxa-profile-server/CHANGELOG.md
  packages/fxa-profile-server/npm-shrinkwrap.json
  packages/fxa-profile-server/package.json
Labels: P1

#758 chore(repo):remove husky and associated git hooks
  packages/fxa-auth-server/npm-shrinkwrap.json
  packages/fxa-auth-server/package.json
  packages/fxa-content-server/npm-shrinkwrap.json
  packages/fxa-content-server/package.json
Labels: P3, cat:code quality

#733 chore(packages): remove old release tagging scripts and docs
  packages/fxa-auth-db-mysql/grunttasks/bump.js
  packages/fxa-auth-db-mysql/grunttasks/changelog.js
  packages/fxa-auth-db-mysql/grunttasks/version.js
  packages/fxa-auth-db-mysql/npm-shrinkwrap.json
  packages/fxa-auth-db-mysql/package.json
  packages/fxa-auth-server/grunttasks/bump.js
  packages/fxa-auth-server/grunttasks/changelog.js
  packages/fxa-auth-server/grunttasks/version.js
  packages/fxa-auth-server/npm-shrinkwrap.json
  packages/fxa-auth-server/package.json
  packages/fxa-content-server/grunttasks/bump.js
  packages/fxa-content-server/grunttasks/changelog.js
  packages/fxa-content-server/grunttasks/version.js
  packages/fxa-content-server/npm-shrinkwrap.json
  packages/fxa-content-server/package.json
  packages/fxa-customs-server/README.md
  packages/fxa-customs-server/grunttasks/bump.js
  packages/fxa-customs-server/grunttasks/changelog.js
  packages/fxa-customs-server/grunttasks/version.js
  packages/fxa-customs-server/npm-shrinkwrap.json
  packages/fxa-customs-server/package.json
  packages/fxa-email-event-proxy/README.md
  packages/fxa-email-service/RELEASE.md
  packages/fxa-email-service/scripts/release.sh
  packages/fxa-profile-server/npm-shrinkwrap.json
  packages/fxa-profile-server/package.json
  packages/fxa-profile-server/tasks/bump.js
  packages/fxa-profile-server/tasks/changelog.js
  packages/fxa-profile-server/tasks/version.js
Labels: P3, cat:code quality

#730 fix(scripts): ensure release script pulls changes from private/master
  release.sh
Labels: P1, status:bug

#804 fix(ci): run all auth server tests in ci
  packages/fxa-auth-server/Dockerfile-test
  packages/fxa-auth-server/package.json
Labels: P1, status:bug

#823 refactor(broker): pull string_type! macro out to the types directory
  packages/fxa-event-broker/Cargo.lock
  packages/fxa-event-broker/Cargo.toml
  packages/fxa-event-broker/src/settings.rs
  packages/fxa-event-broker/src/settings/test.rs
  packages/fxa-event-broker/src/types.rs
  packages/fxa-event-broker/src/types/aws.rs
  packages/fxa-event-broker/src/types/aws/test.rs
  packages/fxa-event-broker/src/types/env.rs
  packages/fxa-event-broker/src/types/env/test.rs
  packages/fxa-event-broker/src/types/error.rs
  packages/fxa-event-broker/src/types/macros.rs
  packages/fxa-event-broker/src/types/validate.rs
  packages/fxa-event-broker/src/types/validate/test.rs
Labels: P2

#888 fix(settings views): Refresh status button text fixed
  packages/fxa-content-server/app/scripts/templates/settings/account_recovery/account_recovery.mustache
  packages/fxa-content-server/app/scripts/templates/settings/clients.mustache
  packages/fxa-content-server/app/scripts/templates/settings/emails.mustache
  packages/fxa-content-server/app/scripts/templates/settings/two_step_authentication.mustache
  packages/fxa-content-server/app/scripts/templates/settings/upgrade_session.mustache
Labels: needs:gpg signature

#874 remove mozlog.config() fxa-auth-server-I467
  packages/fxa-auth-server/lib/log.js
  packages/fxa-auth-server/test/local/log.js
Labels: needs:gpg signature

#850 fix(style): removed select-row
  packages/fxa-content-server/app/scripts/views/tooltip.js
  packages/fxa-content-server/app/styles/_modules.scss
  packages/fxa-content-server/app/styles/modules/_select-row.scss
Labels: needs:gpg signature

#915 chore(tests): Add token code tests to circle
  packages/fxa-content-server/tests/functional_circle.js
Labels: fxa-content-server

#879 chore(styles): Remove all references to trustedUI and resonableUI
  packages/fxa-content-server/app/styles/_base.scss
  packages/fxa-content-server/app/styles/_breakpoints.scss
  packages/fxa-content-server/app/styles/_layout.scss
  packages/fxa-content-server/app/styles/modules/_avatar.scss
  packages/fxa-content-server/app/styles/modules/_branding.scss
  packages/fxa-content-server/app/styles/modules/_custom-rows.scss
  packages/fxa-content-server/app/styles/modules/_graphic.scss
  packages/fxa-content-server/app/styles/modules/_input-row.scss
  packages/fxa-content-server/app/styles/modules/_legal.scss
  packages/fxa-content-server/app/styles/modules/_marketing-ios.scss
  packages/fxa-content-server/app/styles/modules/_spinner.scss
  packages/fxa-content-server/app/styles/modules/_tooltip.scss
Labels: needs:gpg signature

#960 fix(lint): Fix the lint error in the fennec_v1_email_first test.
  packages/fxa-content-server/tests/functional/fx_fennec_v1_email_first.js
Labels: cat:code quality, fxa-content-server
