Repository mozilla/fxa, pull requests merged in 2019-12, with the labels that each got.

#3607 fix(fenix): Do not use Sync Optional with Fenix
  packages/fxa-content-server/app/scripts/models/auth_brokers/base.js
  packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync.js
  packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-webchannel-v1.js
  packages/fxa-content-server/app/scripts/views/mixins/signup-mixin.js
  packages/fxa-content-server/app/tests/spec/models/auth_brokers/fx-sync.js
  packages/fxa-content-server/app/tests/spec/views/mixins/signup-mixin.js
  packages/fxa-content-server/tests/functional/oauth_webchannel.js
  packages/fxa-content-server/tests/functional/sync_v3_sign_up.js
Labels: needs:uplift

#3595 feat(signin): Convert signin w/ unverified account to codes
  packages/fxa-auth-server/lib/routes/utils/signin.js
  packages/fxa-auth-server/test/local/routes/utils/signin.js
  packages/fxa-content-server/app/scripts/lib/auth-errors.js
  packages/fxa-content-server/app/scripts/lib/verification-methods.ts
  packages/fxa-content-server/app/scripts/models/account.js
  packages/fxa-content-server/app/scripts/views/mixins/signin-mixin.js
  packages/fxa-content-server/app/tests/spec/models/account.js
  packages/fxa-content-server/tests/functional/fx_fennec_v1_force_auth.js
  packages/fxa-content-server/tests/functional/fx_fennec_v1_sign_in.js
  packages/fxa-content-server/tests/functional/fx_ios_v1_sign_in.js
  packages/fxa-content-server/tests/functional/oauth_permissions.js
  packages/fxa-content-server/tests/functional/oauth_prompt_none.js
  packages/fxa-content-server/tests/functional/oauth_sign_in.js
  packages/fxa-content-server/tests/functional/settings_common.js
  packages/fxa-content-server/tests/functional/sign_in_blocked.js
  packages/fxa-content-server/tests/functional/sign_up.js
  packages/fxa-content-server/tests/functional/sync_v3_sign_in.js
Labels: needs:qa

#3634 Set `service` tag for metrics events based on fxa_status response.
  packages/fxa-content-server/app/scripts/lib/metrics.js
  packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync.js
  packages/fxa-content-server/app/tests/spec/lib/metrics.js
  packages/fxa-content-server/app/tests/spec/models/auth_brokers/fx-sync.js
Labels: needs:uplift

#3778 fix(content-server): separate client and server sentry dsn
  packages/fxa-content-server/server/lib/configuration.js
  packages/fxa-content-server/server/lib/routes/get-index.js
Labels: needs:ops
