Repository mozilla/fxa, pull requests merged in 2019-11, with the labels that each got.

#3314 fix(metrics): Restore high volume oauth events from amplitude logging
  packages/fxa-auth-server/fxa-oauth-server/lib/metrics/amplitude.js
  packages/fxa-auth-server/fxa-oauth-server/test/metrics/amplitude.js
Labels: needs:uplift

#2570 feat(keys): Explicitly track timestamp of last key rotation.
  packages/fxa-auth-db-mysql/db-server/test/backend/db_tests.js
  packages/fxa-auth-db-mysql/db-server/test/backend/remote.js
  packages/fxa-auth-db-mysql/lib/db/mem.js
  packages/fxa-auth-db-mysql/lib/db/mysql.js
  packages/fxa-auth-db-mysql/lib/db/patch.js
  packages/fxa-auth-db-mysql/lib/db/schema/patch-104-105.sql
  packages/fxa-auth-db-mysql/lib/db/schema/patch-105-106.sql
  packages/fxa-auth-db-mysql/lib/db/schema/patch-106-105.sql
  packages/fxa-auth-server/lib/routes/account.js
  packages/fxa-auth-server/lib/routes/password.js
  packages/fxa-auth-server/test/remote/oauth_tests.js
  packages/fxa-auth-server/test/remote/password_change_tests.js
  packages/fxa-auth-server/test/remote/recovery_key_tests.js
Labels: needs:uplift

#3351 feat(metrics): Allow RPs to submit a generic 'engage' event to amplitude
  packages/fxa-content-server/server/lib/amplitude.js
  packages/fxa-content-server/server/lib/routes/get-metrics-flow.js
  packages/fxa-content-server/tests/server/amplitude.js
  packages/fxa-content-server/tests/server/routes/get-metrics-flow.js
  packages/fxa-shared/metrics/amplitude.js
Labels: needs:uplift

#3426 fix(sync): clean up and fix sync preference options for Firefox 71
  packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync-channel.js
  packages/fxa-content-server/app/scripts/models/reliers/browser.js
  packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js
  packages/fxa-content-server/app/scripts/views/mixins/do-not-sync-mixin.js
  packages/fxa-content-server/app/scripts/views/would_you_like_to_sync.js
  packages/fxa-content-server/app/tests/spec/models/auth_brokers/fx-sync-channel.js
  packages/fxa-content-server/app/tests/spec/views/mixins/do-not-sync-mixin.js
Labels: P1

#3455 OAuth CORS
  packages/fxa-auth-server/lib/oauth/routes/index.js
Labels: needs:uplift

#3436 feat(signup): fix #3197 - Autocomplete common email domains during signup for better UX
  packages/fxa-content-server/app/scripts/lib/user-agent.js
  packages/fxa-content-server/app/scripts/templates/index.mustache
  packages/fxa-content-server/app/scripts/templates/partial/email-autocomplete-domains.mustache
  packages/fxa-content-server/app/scripts/views/index.js
  packages/fxa-content-server/app/scripts/views/mixins/email-autocomplete-domains-mixin.js
  packages/fxa-content-server/app/styles/modules/_input-row.scss
  packages/fxa-content-server/app/tests/spec/views/mixins/email-autocomplete-domains-mixin.js
  packages/fxa-content-server/app/tests/test_start.js
  packages/fxa-content-server/tests/functional/lib/selectors.js
Labels: status:qa+
