Repository mozilla/fxa, pull requests merged in 2020-08, with the labels that each got.

#6141 feat(settings): add session verified state to graphql-api
  packages/fxa-auth-client/lib/client.ts
  packages/fxa-graphql-api/src/lib/auth.ts
  packages/fxa-graphql-api/src/lib/resolvers/account-resolver.ts
  packages/fxa-graphql-api/src/lib/resolvers/session-resolver.ts
  packages/fxa-graphql-api/src/lib/resolvers/types/session.ts
  packages/fxa-graphql-api/src/lib/server.ts
  packages/fxa-graphql-api/src/test/lib/auth.spec.ts
  packages/fxa-graphql-api/src/test/lib/datasources/authServer.spec.ts
  packages/fxa-graphql-api/src/test/lib/datasources/profileServer.spec.ts
  packages/fxa-graphql-api/src/test/lib/mocks.ts
  packages/fxa-graphql-api/src/test/lib/resolvers/account-resolver.spec.ts
  packages/fxa-graphql-api/src/test/lib/schema.spec.ts
  packages/fxa-graphql-api/src/test/lib/server.spec.ts
  packages/fxa-settings/src/components/AccountDataHOC/index.tsx
  packages/fxa-settings/src/components/VerifiedSessionGuard/index.test.tsx
  packages/fxa-settings/src/components/VerifiedSessionGuard/index.tsx
  packages/fxa-settings/src/lib/auth.ts
  packages/fxa-settings/src/lib/cache.ts
Labels: fxa-content-server, 🙈 skip ci

#6106 chore(experiment): remove the qr cad experiment and apply winning treatments
  packages/fxa-content-server/app/scripts/lib/constants.js
  packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js
  packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/newsletter-cad-chooser.js
  packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/qr-code-cad.js
  packages/fxa-content-server/app/scripts/views/connect_another_device.js
  packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js
  packages/fxa-content-server/app/scripts/views/mixins/verification-reason-mixin.js
  packages/fxa-content-server/app/scripts/views/pair/index.js
  packages/fxa-content-server/app/scripts/views/post_verify/cad_qr/get_started.js
  packages/fxa-content-server/app/tests/spec/lib/experiments/grouping-rules/index.js
  packages/fxa-content-server/app/tests/spec/views/connect_another_device.js
  packages/fxa-content-server/app/tests/spec/views/post_verify/cad_qr/get_started.js
  packages/fxa-content-server/tests/functional/connect_another_device.js
  packages/fxa-content-server/tests/functional/fx_fennec_v1_force_auth.js
  packages/fxa-content-server/tests/functional/fx_fennec_v1_settings.js
  packages/fxa-content-server/tests/functional/fx_fennec_v1_sign_in.js
  packages/fxa-content-server/tests/functional/lib/selectors.js
  packages/fxa-content-server/tests/functional/oauth_sync_sign_in.js
  packages/fxa-content-server/tests/functional/post_verify/account_recovery.js
  packages/fxa-content-server/tests/functional/post_verify/cad_qr.js
  packages/fxa-content-server/tests/functional/settings_secondary_emails.js
  packages/fxa-content-server/tests/functional/sign_in_cached.js
  packages/fxa-content-server/tests/functional/sync_v3_force_auth.js
  packages/fxa-content-server/tests/functional/sync_v3_settings.js
  packages/fxa-content-server/tests/functional/sync_v3_sign_in.js
  packages/fxa-content-server/tests/functional/sync_v3_sign_up.js
Labels: needs:qa

#6221 chore(docs): Update fxa-settings docs
  packages/fxa-settings/README.md
Labels: 🙈 skip ci

#6224 Settings: remove recovery key
  packages/fxa-graphql-api/src/lib/datasources/authServer.ts
  packages/fxa-graphql-api/src/lib/resolvers/account-resolver.ts
  packages/fxa-graphql-api/src/lib/resolvers/types/input/delete-recovery-key.ts
  packages/fxa-graphql-api/src/lib/resolvers/types/input/index.ts
  packages/fxa-graphql-api/src/test/lib/datasources/authServer.spec.ts
  packages/fxa-graphql-api/src/test/lib/resolvers/account-resolver.spec.ts
  packages/fxa-react/components/Portal/index.tsx
  packages/fxa-settings/src/components/Modal/index.stories.tsx
  packages/fxa-settings/src/components/Modal/index.tsx
  packages/fxa-settings/src/components/ModalVerifySession/index.stories.tsx
  packages/fxa-settings/src/components/ModalVerifySession/index.test.tsx
  packages/fxa-settings/src/components/ModalVerifySession/index.tsx
  packages/fxa-settings/src/components/Security/index.stories.tsx
  packages/fxa-settings/src/components/Security/index.test.tsx
  packages/fxa-settings/src/components/Security/index.tsx
  packages/fxa-settings/src/components/UnitRow/index.stories.tsx
  packages/fxa-settings/src/components/UnitRow/index.test.tsx
  packages/fxa-settings/src/components/UnitRow/index.tsx
  packages/fxa-settings/src/components/UnitRowRecoveryKey/index.stories.tsx
  packages/fxa-settings/src/components/UnitRowRecoveryKey/index.test.tsx
  packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx
  packages/fxa-settings/src/components/VerifiedSessionGuard/index.test.tsx
  packages/fxa-settings/src/components/VerifiedSessionGuard/index.tsx
  packages/fxa-settings/src/models/_mocks.tsx
Labels: fxa-content-server, 🙈 skip ci

#6331 fxa-mono docker image
  .circleci/build-all.sh
  .circleci/build.sh
  .circleci/deploy-all.sh
  .dockerignore
  _dev/docker/mono/Dockerfile
  _scripts/build-fxa-mono.sh
  _scripts/build-fxa-node.sh
  packages/fxa-auth-server/Dockerfile
  packages/fxa-auth-server/config/index.ts
  packages/fxa-auth-server/docs/api.md
  packages/fxa-auth-server/docs/device_registration.md
  packages/fxa-auth-server/lib/pushpayloads.schema.json
  packages/fxa-auth-server/lib/routes/devices-and-sessions.js
  packages/fxa-auth-server/package.json
  packages/fxa-auth-server/test/local/push.js
  packages/fxa-customs-server/Dockerfile
  packages/fxa-graphql-api/.dockerignore
Labels: 🙈 skip ci
